export async function GET(request: Request) {
  try {
    // Mock data for demonstration
    const mockDocuments = [
      {
        id: 1,
        title: "Calculus I Mid-term Examination 2024",
        course_code: "MATH101",
        course_name: "Calculus I",
        year: 2024,
        semester: 1,
        exam_type: "semester",
        school_name: "School of Science",
        department_name: "Mathematics",
        file_path: "https://example.com/papers/calc1-midterm-2024.pdf",
        download_count: 145,
        resource_type_name: "Past Papers",
        author: null,
        publication_date: null,
        abstract: null,
      },
      {
        id: 2,
        title: "Applied Calculus in Engineering Simulations",
        course_code: "ENG201",
        course_name: "Engineering Mathematics",
        year: 2023,
        semester: 2,
        exam_type: "final",
        school_name: "School of Engineering",
        department_name: "Civil Engineering",
        file_path: "https://example.com/journals/applied-calc-eng.pdf",
        download_count: 82,
        resource_type_name: "Journal",
        author: "Dr. A. Phiri",
        publication_date: "2023-06-15",
        abstract: "An exploration of calculus applications in modern engineering projects.",
      },
      {
        id: 3,
        title: "Numerical Methods in Differential Calculus",
        course_code: "MATH201",
        course_name: "Numerical Methods",
        year: 2022,
        semester: 1,
        exam_type: "continuous",
        school_name: "School of Science",
        department_name: "Mathematics",
        file_path: "https://example.com/dissertations/numerical-methods.pdf",
        download_count: 37,
        resource_type_name: "Dissertations",
        author: "C. Banda",
        publication_date: "2022-05-20",
        abstract: "A comprehensive study on numerical approaches to solving differential equations.",
      },
      {
        id: 4,
        title: "MATH101 Course Outline — Calculus I",
        course_code: "MATH101",
        course_name: "Calculus I",
        year: 2024,
        semester: 1,
        exam_type: null,
        school_name: "School of Science",
        department_name: "Mathematics",
        file_path: "https://example.com/outlines/math101-outline.pdf",
        download_count: 210,
        resource_type_name: "Course Outlines",
        author: null,
        publication_date: null,
        abstract: null,
      },
      {
        id: 5,
        title: "Stochastic Calculus in Financial Modelling",
        course_code: "BUS301",
        course_name: "Financial Mathematics",
        year: 2023,
        semester: 1,
        exam_type: null,
        school_name: "School of Business",
        department_name: "Finance",
        file_path: "https://example.com/research/stochastic-calculus.pdf",
        download_count: 56,
        resource_type_name: "Research Papers",
        author: "Prof. M. Dube",
        publication_date: "2023-03-10",
        abstract: "Modern applications of stochastic calculus in quantitative finance and risk management.",
      },
      {
        id: 6,
        title: "Calculus II End-of-Semester Exam 2023",
        course_code: "MATH201",
        course_name: "Calculus II",
        year: 2023,
        semester: 2,
        exam_type: "final",
        school_name: "School of Science",
        department_name: "Mathematics",
        file_path: "https://example.com/papers/calc2-final-2023.pdf",
        download_count: 198,
        resource_type_name: "Past Papers",
        author: null,
        publication_date: null,
        abstract: null,
      },
    ];

    return new Response(
      JSON.stringify({
        success: true,
        data: mockDocuments,
      }),
      { status: 200 }
    );
  } catch (error) {
    console.error('[v0] Error fetching documents:', error);
    return new Response(
      JSON.stringify({
        success: false,
        error: 'Failed to fetch documents',
      }),
      { status: 500 }
    );
  }
}
